# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 23:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glucoses', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='default_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glucoses.Category'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='glucose_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='glucoses.Unit'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
