# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 20:54
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180128_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='America/Regina'),
        ),
    ]
