# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180220_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='default_category',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='glucose_high',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='glucose_low',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='glucose_target_max',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='glucose_target_min',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='glucose_unit',
        ),
    ]
