# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_auto_20180209_1138'),
        ('coins', '0002_auto_20180210_1347'),
    ]

    operations = [
    ]
