# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_auto_20180228_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=8),
        ),
    ]
