# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_auto_20180228_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
