# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('time_zone', timezone_field.fields.TimeZoneField(default='US/Eastern')),
                ('glucose_low', models.PositiveIntegerField(default=60)),
                ('glucose_high', models.PositiveIntegerField(default=180)),
                ('glucose_target_min', models.PositiveIntegerField(default=70)),
                ('glucose_target_max', models.PositiveIntegerField(default=120)),
            ],
            options={
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
