# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlineText', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=512)),
                ('createdAt', models.DateTimeField()),
                ('url', models.CharField(max_length=256)),
                ('newsAgency', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('createdAt', models.DateTimeField()),
                ('url', models.CharField(max_length=256)),
                ('subreddit', models.CharField(max_length=128)),
                ('comments', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('retweetCount', models.IntegerField(default=0)),
                ('likesCount', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField()),
                ('username', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=512)),
            ],
        ),
    ]
