# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 22:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='subreddit',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Please do not include the /r/ of the subreddit', regex='^\\/r\\/')]),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator]),
        ),
    ]
