# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 22:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialMedia', '0002_auto_20180212_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator]),
        ),
    ]
